# Generated by Django 4.1.2 on 2024-07-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio_app', '0002_rename_navbar_item_navbaritem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(default='default.png', upload_to='static/images/'),
        ),
    ]
